export const SPELL_TYPES = {
    WILD: "wild",
    SOURCE: "source",
    QUALITY: "quality",
    DELIVERY: "delivery"
};

export const SPELL_GLYPHS = {
    ARCANE: "arcane",
    DARK: "dark",
    PRIMAL: "primal",
    ELEMENTAL: "elemental",
    ILLUSION: "illusion"
};

export const SPELL_MODEL = {
    id: "",
    name: "",
    text: "",
    glyph: "",
    type: "",
    initiative: 0
};

export const SPELL_CARDS = {
    WILD_MAGIC: {
        id: "WILD_MAGIC",
        name: "Wild Magic",
        text: "Use in place of any one card in a spell. Before resolving any card of the spell, reveal cards from the top of the Main Deck until you find a card of the type this Wild Magic card was used in place of. That card becomes part of your spell. Discard this Wild Magic card and the rest of the revealed cards.",
        glyph: "",
        type: SPELL_TYPES.WILD,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    BEARD_O_BLASTYS: {
        id: "BEARD_O_BLASTYS",
        name: "Beard 'O Blasty's",
        text: "This card copies the text of the Delivery of your spell.",
        glyph: SPELL_GLYPHS.ARCANE,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    BEN_VOODOOS: {
        id: "BEN_VOODOOS",
        name: "Ben Voodoo's",
        text: "Each foe rolls a die and takes that much damage. Destroy one of your Treasures if you have any.",
        glyph: SPELL_GLYPHS.DARK,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    BLEEMAX_BRAINIACS: {
        id: "BLEEMAX_BRAINIACS",
        name: "Bleemax Brainiac's",
        text: "Reveal the top two cards of the Main Deck. Each one with a glyph that matches a glyph in your spell is added to your spell. Discard the rest.",
        glyph: SPELL_GLYPHS.ARCANE,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    DR_ROOTY_BARKS: {
        id: "DR_ROOTY_BARKS",
        name: "Dr. Rooty Bark's",
        text: "You heal 3 HP. Each foe rolls a die. Each foe who rolls a 6 heals 3 HP.",
        glyph: SPELL_GLYPHS.PRIMAL,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    KING_OBERONS: {
        id: "KING_OBERONS",
        name: "King Oberon's",
        text: "Heal 2 HP.",
        glyph: SPELL_GLYPHS.PRIMAL,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    MAGMA_GOGS: {
        id: "MAGMA_GOGS",
        name: "Magma Gog's",
        text: "Choose one: Deal 3 damage to the foe on your left OR deal 1 damage to each foe.",
        glyph: SPELL_GLYPHS.ELEMENTAL,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    MIDNIGHT_MERLINS: {
        id: "MIDNIGHT_MERLINS",
        name: "Midnight Merlin's",
        text: "Deal 1 damage to your strongest foe for each living Wizard. Then draw a Dead Wizard card.",
        glyph: SPELL_GLYPHS.DARK,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    MUZZLESNAPS: {
        id: "MUZZLESNAPS",
        name: "Muzzlesnap's",
        text: "Add a die to each of your Power Rolls this round.",
        glyph: SPELL_GLYPHS.PRIMAL,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    OLD_SCRATCHS: {
        id: "OLD_SCRATCHS",
        name: "Old Scratch's",
        text: "Roll a die. If you roll 1-3, you suffer that much damage. If you roll 4-6, you heal that many HP.",
        glyph: SPELL_GLYPHS.DARK,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    PAM_AND_HECUBAS: {
        id: "PAM_AND_HECUBAS",
        name: "Pam and Hecuba's",
        text: "Your Delivery targets each foe instead.",
        glyph: SPELL_GLYPHS.ILLUSION,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    PEW_AND_PEWS: {
        id: "PEW_AND_PEWS",
        name: "Pew and Pew's",
        text: "Reveal the top four cards of the Main Deck. Add any revealed Source cards to your spell and discard the rest.",
        glyph: SPELL_GLYPHS.ILLUSION,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    PROFESSOR_PRESTOS: {
        id: "PROFESSOR_PRESTOS",
        name: "Professor Presto's",
        text: "Deal 3 damage to a random foe. If you played a Wild Magic card as part of your spell, gain a Treasure.",
        glyph: SPELL_GLYPHS.ARCANE,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    ROSE_BOTTOMS: {
        id: "ROSE_BOTTOMS",
        name: "Rose Bottom's",
        text: "Heal 1 HP for each different glyph in your spell.",
        glyph: SPELL_GLYPHS.PRIMAL,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    SCORCHIAS: {
        id: "SCORCHIAS",
        name: "Scorchia's",
        text: "Deal 3 damage to your strongest foe.",
        glyph: SPELL_GLYPHS.ELEMENTAL,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    SIR_LOOTZORS: {
        id: "SIR_LOOTZORS",
        name: "Sir Lootzor's",
        text: "You gain a Treasure. Each foe rolls a die. Each foe that rolls a 6 gains a Treasure.",
        glyph: SPELL_GLYPHS.ARCANE,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    SPHINXIONS: {
        id: "SPHINXIONS",
        name: "Sphinxion's",
        text: "Choose and steal a Treasure belonging to any foe.",
        glyph: SPELL_GLYPHS.ILLUSION,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    THAI_FOONS: {
        id: "THAI_FOONS",
        name: "Thai Foon's",
        text: "Deal 3 damage to each foe who already acted this round.",
        glyph: SPELL_GLYPHS.ELEMENTAL,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    THE_DEATH_FAIRYS: {
        id: "THE_DEATH_FAIRYS",
        name: "The Death Fairy's",
        text: "Deal 2 damage to any foe. If that foe dies, repeat this effect.",
        glyph: SPELL_GLYPHS.DARK,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    WALKER_TIME_RANGERS: {
        id: "WALKER_TIME_RANGERS",
        name: "Walker Time Ranger's",
        text: "Each player rolls a die. Add 1 to your roll for each different glyph in your spell. Deal 3 damage to the lowest roller(s).",
        glyph: SPELL_GLYPHS.ILLUSION,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    WYRMTORS: {
        id: "WYRMTORS",
        name: "Wyrmtor's",
        text: "Deal 1 damage to each foe for each different glyph in your spell.",
        glyph: SPELL_GLYPHS.ELEMENTAL,
        type: SPELL_TYPES.SOURCE,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    BALLSY: {
        id: "BALLSY",
        name: "Ballsy",
        text: "The foes to your left and to your right must each choose one of his Treasures and give it to you or suffer 3 damage.",
        glyph: SPELL_GLYPHS.ILLUSION,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    BOULDERIFFIC: {
        id: "BOULDERIFFIC",
        name: "Boulder-iffic",
        text: "Deal 1 damage to the foe on your left, 2 damage to the foe on his left, 3 damage to the next foe to the left, and so on, until you've damage each foe once.",
        glyph: SPELL_GLYPHS.PRIMAL,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    CATASTROPHIC: {
        id: "CATASTROPHIC",
        name: "Cat-a-strophic",
        text: "Each player rolls a die. Add 2 to your roll. The high roller(s) gains a Treasure. Each other player takes damage equal to his roll.",
        glyph: SPELL_GLYPHS.ILLUSION,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    DELICIOUS: {
        id: "DELICIOUS",
        name: "Delicious",
        text: "Foes with an odd number of HP each take 1 damage for each different glyph in your spell.",
        glyph: SPELL_GLYPHS.ELEMENTAL,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    DEVILICIOUS: {
        id: "DEVILICIOUS",
        name: "Devilicious",
        text: "",
        glyph: SPELL_GLYPHS.DARK,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    DICEY: {
        id: "DICEY",
        name: "Dicey",
        text: "You roll two dice. Each of your foes rolls one die. Foes who match one or more of your die rolls each suffer damage equal to that roll.",
        glyph: SPELL_GLYPHS.ELEMENTAL,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    DISCOMIRRORED: {
        id: "DISCOMIRRORED",
        name: "Disco-mirrored",
        text: "This card copies the text of a Source or Delivery in your spell.",
        glyph: SPELL_GLYPHS.ILLUSION,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    EXPLODIFYING: {
        id: "EXPLODIFYING",
        name: "Explodifying",
        text: "",
        glyph: SPELL_GLYPHS.ELEMENTAL,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    FESTERING: {
        id: "FESTERING",
        name: "Festering",
        text: "Your strongest foe who has not acted this round must discard the Quality of his spell, if any.",
        glyph: SPELL_GLYPHS.DARK,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    IMPATIENT: {
        id: "IMPATIENT",
        name: "Impatient",
        text: "At the start of the initiative, reveal this card. Your spell resolves first this round. Deal 1 damage to each foe.",
        glyph: SPELL_GLYPHS.ARCANE,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    INFERNOTASTIC: {
        id: "INFERNOTASTIC",
        name: "Inferno-tastic",
        text: "Deal 1 damage to each foe for each Elemental glyph in your spell.",
        glyph: SPELL_GLYPHS.ELEMENTAL,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    MAGGOTY: {
        id: "MAGGOTY",
        name: "Maggoty",
        text: "Deal 2 damage to your strongest foe for each Dark glyph in your spell.",
        glyph: SPELL_GLYPHS.DARK,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    MIGHTYGRO: {
        id: "MIGHTYGRO",
        name: "Mighty-gro",
        text: "Heal 2 HP. Then, if you are the weakest player, add a random card from your hand to your spell.",
        glyph: SPELL_GLYPHS.PRIMAL,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    MINDALTERING: {
        id: "MINDALTERING",
        name: "Mind-altering",
        text: "Deal 3 damage to a random foe. You and that foe each gain a Treasure.",
        glyph: SPELL_GLYPHS.ILLUSION,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    MYSTERIOUS: {
        id: "MYSTERIOUS",
        name: "Mysterious",
        text: "Deal 1 damage to the foe on your right for each different glyph in your spell and each Treasure you have.",
        glyph: SPELL_GLYPHS.ARCANE,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    POLISHED: {
        id: "POLISHED",
        name: "Polished",
        text: "",
        glyph: SPELL_GLYPHS.ARCANE,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    PRICKLY: {
        id: "PRICKLY",
        name: "Prickly",
        text: "",
        glyph: SPELL_GLYPHS.PRIMAL,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    RITUALISTIC: {
        id: "RITUALISTIC",
        name: "Ritualistic",
        text: "",
        glyph: SPELL_GLYPHS.DARK,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    THUNDERING: {
        id: "THUNDERING",
        name: "Thundering",
        text: "Deal 2 damage to a random foe. Do this once for each different glyph in your spell.",
        glyph: SPELL_GLYPHS.PRIMAL,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    TWOFACED: {
        id: "TWOFACED",
        name: "Two-faced",
        text: "A player of your choice gains a Treasure. Then, deal 2 damage to that player for each Treasure he has.",
        glyph: SPELL_GLYPHS.ARCANE,
        type: SPELL_TYPES.QUALITY,
        initiative: 0,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    BEDAZZLEMENT: {
        id: "BEDAZZLEMENT",
        name: "Bedazzlement",
        text: "",
        glyph: SPELL_GLYPHS.ILLUSION,
        type: SPELL_TYPES.DELIVERY,
        initiative: 19,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    BRAINSUCK: {
        id: "BRAINSUCK",
        name: "Brain-suck",
        text: "",
        glyph: SPELL_GLYPHS.ILLUSION,
        type: SPELL_TYPES.DELIVERY,
        initiative: 15,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    CHICKEN: {
        id: "CHICKEN",
        name: "Chicken",
        text: "",
        glyph: SPELL_GLYPHS.ELEMENTAL,
        type: SPELL_TYPES.DELIVERY,
        initiative: 3,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    CONE_OF_ACID: {
        id: "CONE_OF_ACID",
        name: "Cone of Acid",
        text: "",
        glyph: SPELL_GLYPHS.ARCANE,
        type: SPELL_TYPES.DELIVERY,
        initiative: 4,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    DEATH_WISH: {
        id: "DEATH_WISH",
        name: "Death Wish",
        text: "",
        glyph: SPELL_GLYPHS.DARK,
        type: SPELL_TYPES.DELIVERY,
        initiative: 8,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    DRAGON_HOARD: {
        id: "DRAGON_HOARD",
        name: "Dragon Hoard",
        text: "",
        glyph: SPELL_GLYPHS.ARCANE,
        type: SPELL_TYPES.DELIVERY,
        initiative: 6,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    EXORCISM: {
        id: "EXORCISM",
        name: "Exorcism",
        text: "",
        glyph: SPELL_GLYPHS.DARK,
        type: SPELL_TYPES.DELIVERY,
        initiative: 11,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    FIST_O_NATURE: {
        id: "FIST_O_NATURE",
        name: "Fist O' Nature",
        text: "",
        glyph: SPELL_GLYPHS.PRIMAL,
        type: SPELL_TYPES.DELIVERY,
        initiative: 14,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    FOUNTAIN_OF_YOUTH: {
        id: "FOUNTAIN_OF_YOUTH",
        name: "Fountain of Youth",
        text: "",
        glyph: SPELL_GLYPHS.PRIMAL,
        type: SPELL_TYPES.DELIVERY,
        initiative: 12,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    GORENADO: {
        id: "GORENADO",
        name: "Gore-nado",
        text: "",
        glyph: SPELL_GLYPHS.PRIMAL,
        type: SPELL_TYPES.DELIVERY,
        initiative: 2,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    LIGHTNING_BOLT: {
        id: "LIGHTNING_BOLT",
        name: "Lightning Bolt",
        text: "",
        glyph: SPELL_GLYPHS.ELEMENTAL,
        type: SPELL_TYPES.DELIVERY,
        initiative: 9,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    MEATIERSWARM: {
        id: "MEATIERSWARM",
        name: "Meatier-swarm",
        text: "",
        glyph: SPELL_GLYPHS.ELEMENTAL,
        type: SPELL_TYPES.DELIVERY,
        initiative: 20,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    MERCYKILLING: {
        id: "MERCYKILLING",
        name: "Mercy-killing",
        text: "",
        glyph: SPELL_GLYPHS.DARK,
        type: SPELL_TYPES.DELIVERY,
        initiative: 5,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    NUKEULUR_MELTDOWN: {
        id: "NUKEULUR_MELTDOWN",
        name: "Nuke-u-lur Meltdown",
        text: "",
        glyph: SPELL_GLYPHS.ELEMENTAL,
        type: SPELL_TYPES.DELIVERY,
        initiative: 10,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    PACT_WITH_THE_DEVIL: {
        id: "PACT_WITH_THE_DEVIL",
        name: "Pact with the Devil",
        text: "",
        glyph: SPELL_GLYPHS.DARK,
        type: SPELL_TYPES.DELIVERY,
        initiative: 18,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    PHANTASMAGOONS: {
        id: "PHANTASMAGOONS",
        name: "Phantasmagoons",
        text: "",
        glyph: SPELL_GLYPHS.ILLUSION,
        type: SPELL_TYPES.DELIVERY,
        initiative: 17,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    POWER_VORTEX: {
        id: "POWER_VORTEX",
        name: "Power Vortex",
        text: "",
        glyph: SPELL_GLYPHS.ARCANE,
        type: SPELL_TYPES.DELIVERY,
        initiative: 16,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    SNAKEDANCE: {
        id: "SNAKEDANCE",
        name: "Snakedance",
        text: "",
        glyph: SPELL_GLYPHS.PRIMAL,
        type: SPELL_TYPES.DELIVERY,
        initiative: 1,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    TESTIKILL: {
        id: "TESTIKILL",
        name: "Testikill",
        text: "",
        glyph: SPELL_GLYPHS.ARCANE,
        type: SPELL_TYPES.DELIVERY,
        initiative: 7,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    },
    VORPALTRAP: {
        id: "VORPALTRAP",
        name: "Vorpal-trap",
        text: "",
        glyph: SPELL_GLYPHS.ILLUSION,
        type: SPELL_TYPES.DELIVERY,
        initiative: 13,
        rolls: [],
        target: "",
        targetEffects: [],
        selfEffects: []
    }
};

export const STARTING_DECK = {
    WILD_MAGIC: 8,
    BEARD_O_BLASTYS: 2,
    BEN_VOODOOS: 2,
    BLEEMAX_BRAINIACS: 2,
    DR_ROOTY_BARKS: 2,
    KING_OBERONS: 2,
    MAGMA_GOGS: 2,
    MIDNIGHT_MERLINS: 2,
    MUZZLESNAPS: 2,
    OLD_SCRATCHS: 2,
    PAM_AND_HECUBAS: 2,
    PEW_AND_PEWS: 2,
    PROFESSOR_PRESTOS: 2,
    ROSE_BOTTOMS: 2,
    SCORCHIAS: 2,
    SIR_LOOTZORS: 2,
    SPHINXIONS: 2,
    THAI_FOONS: 2,
    THE_DEATH_FAIRYS: 2,
    WALKER_TIME_RANGERS: 2,
    WYRMTORS: 2,
    BALLSY: 2,
    BOULDERIFFIC: 2,
    CATASTROPHIC: 2,
    DELICIOUS: 2,
    DEVILICIOUS: 2,
    DICEY: 2,
    DISCOMIRRORED: 2,
    EXPLODIFYING: 2,
    FESTERING: 2,
    IMPATIENT: 2,
    INFERNOTASTIC: 2,
    MAGGOTY: 2,
    MIGHTYGRO: 2,
    MINDALTERING: 2,
    MYSTERIOUS: 2,
    POLISHED: 2,
    PRICKLY: 2,
    RITUALISTIC: 2,
    THUNDERING: 2,
    TWOFACED: 2,
    BEDAZZLEMENT: 2,
    BRAINSUCK: 2,
    CHICKEN: 2,
    CONE_OF_ACID: 2,
    DEATH_WISH: 2,
    DRAGON_HOARD: 2,
    EXORCISM: 2,
    FIST_O_NATURE: 2,
    FOUNTAIN_OF_YOUTH: 2,
    GORENADO: 2,
    LIGHTNING_BOLT: 2,
    MEATIERSWARM: 2,
    MERCYKILLING: 2,
    NUKEULUR_MELTDOWN: 2,
    PACT_WITH_THE_DEVIL: 2,
    PHANTASMAGOONS: 2,
    POWER_VORTEX: 2,
    SNAKEDANCE: 2,
    TESTIKILL: 2,
    VORPALTRAP: 2
}